---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: fio-job-config
data:
  fio.job: |-
    [global]
    name=fio-seq-write
    filename=fio-seq-write
    rw=write
    bs=16K
    direct=1
    numjobs=4
    time_based
    runtime=900

    [file1]
    size=10G
    ioengine=libaio
    iodepth=16
